### PR TITLE
simpler build for local

### PR DESCRIPTION
**Pull request by tomqwu**
Is this version easier for local build?

### CODE REVIEW

**Comment by c4po** [comment]
where do you find the _--build_ option for _docker-compose up_?
will it force rebuild the image every time?

**Comment by tomqwu** [comment]
Yes, it forces rebuild

```

Usage: up [options] [SERVICE...]

Options:
    -d                         Detached mode: Run containers in the background,
                               print new container names.
                               Incompatible with --abort-on-container-exit.
    --no-color                 Produce monochrome output.
    --no-deps                  Don't start linked services.
    --force-recreate           Recreate containers even if their configuration
                               and image haven't changed.
                               Incompatible with --no-recreate.
    --no-recreate              If containers already exist, don't recreate them.
                               Incompatible with --force-recreate.
    --no-build                 Don't build an image, even if it's missing.
    --build                    Build images before starting containers.
    --abort-on-container-exit  Stops all containers if any container was stopped.
                               Incompatible with -d.
    -t, --timeout TIMEOUT      Use this timeout in seconds for container shutdown
                               when attached or when containers are already
                               running. (default: 10)
    --remove-orphans           Remove containers for services not
                               defined in the Compose file
```

**Comment by SiweiWang** [comment]
Do we want this to rebuild everytime ?

**Comment by tomqwu** [comment]
If we mount the src directly then I would say no...

**Comment by SiweiWang** [comment]
There are some frontend recompilation need to happen ,don't think that would work either

**Comment by c4po** [comment]
ok, it seems this need docker-compose v1.7+. doesn't work with v1.6.0

Can you update the readme to add a pre-request session for the minimal version of docker, docker-compose, etc

**Comment by tomqwu** [comment]
ok done

**Pull request merged**
