### PR TITLE
add query endpoints to /builds

### PR DESCRIPTION
**Pull request by c4po**

### CODE REVIEW

**Comment by SiweiWang** [comment]
it would be nice to have application has query than param 
/builds/?applicaiton=XYZ
That way , we can keep buidling on this for env as well
/build/?application=XYZ&ENV=ABC

And that get rid of the extra endpoint we don't really need

**Comment by c4po** [comment]
i'd like to put the "mandatory" field in url instead of query string to reduce the validation check on parameters and error handle.

**Comment by SiweiWang** [comment]
Why is that , the validation efforts seems the same to me, and use query is cleaner . If you go down the path using param , how do you query all build using env . Obviously, /build/all/:env don't work because the param is same as application

**Comment by c4po** [comment]
to query builds on env, I would like to something like
- /environments/ENVNAME/current  
  - get build info for all application
- /environments/ENVNAME/current?application=XYZ
  - get build info for application XYZ

**Comment by SiweiWang** [comment]
that will lead us the more or less same Api (get list of builds) to 3 different endpoints with different Params and queries. That to me is more complicated. If you worries about branch and application relationship , you will have the Same validation issue for this env endpoint your mentioned above. Let's have a quick (phone or in person) once you have time

**Pull request merged**
